spring:
  application:
    name: review

  config:
    import: optional:configserver:http://config-server-service:8080/

  datasource:
    url: jdbc:postgresql://postgres-service:5432/reviewdb
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# MICROSERVICE URLs
# ==========================================

services:
  job:
    url: http://job-service:8090

  company:
    url: http://company-service:8091

  review:
    url: http://review-service:9092


# ==========================================
# EUREKA
# ==========================================

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://servicereg-service:8761/eureka/

  instance:
    prefer-ip-address: true


# ==========================================
# ACTUATOR + TRACING
# ==========================================

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

    export:
      zipkin:
        endpoint: http://zipkin-service:9411/api/v2/spans