services:

  postgres:
    image: postgres:17
    container_name: job-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jobdb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  job-service:
    image: harinathbandi144/job-service:1.0
    container_name: job-service
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  company-service:
    image: harinathbandi144/company-service:1.0
    container_name: company-service
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/companydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  review-service:
    image: harinathbandi144/review-service:1.0
    container_name: review-service
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviewdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
volumes:
  postgres_data: