services:

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-network

  job:
    image: harinathbandi144/job:latest
    container_name: job
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
    depends_on:
      - postgres
    networks:
      - microservice-network
      - postgres

  company:
    image: harinathbandi144/company:latest
    container_name: company
    ports:
      - "8091:8091"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - servicereg
      - postgres
    networks:
      - microservice-network
      - postgres


  review:
    image: harinathbandi144/review:latest
    container_name: review
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - microservice-network
      - postgres

  config:
    image: harinathbandi144/configservicer:latest
    container_name: configservicer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres


  servicereg:
    image: harinathbandi144/servicereg
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - microservice-network
      - postgres

  apigateway:
    image: harinathbandi144/apigateway:latest
    container_name: apigateway
    ports:
      - "8765:8765"
    networks:
      - microservice-network
      - postgres
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres:

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge
