job:
  url: http://job:8090
company:
  url: http://company:8091
review:
  url: http://review:8092

spring:
  application:
    name: job
  #Config Serviver
  config:
    import: optional:configserver:http://config-server:8080/
  #    profiles:
  #      active: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/jobdb
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

# Circute Breaker

resilience4j:
  circuitbreaker:
    instances:
      companyBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        max-attempts: 5
        wait-duration: 2s

  ratelimiter:
    instances:
      companyService:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0


##management:
#  tracing:
#    sampling:
#      probability: 1.0
#    zipkin:
#        endpoint: http://zipkin:9411/api/v2/spans